### PR TITLE
fixed mysql error

### PR DESCRIPTION
**Pull request by sjbwylbs**
fixed [E] Error 1390: Prepared statement contains too many placeholders

### CODE REVIEW

**Comment by andeya** [comment]
No need. Because you can set the max size in config.

**Comment by andeya** [comment]
Maybe we should change mb to kb?
https://github.com/henrylee2cn/pholcus/blob/master/pholcus_pkg/config.ini#L28

**Comment by sjbwylbs** [comment]
It's mysql's limit.
pls take a look [mysql ref](http://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html)
or [stackoverflow](http://stackoverflow.com/questions/18100782/import-of-50k-records-in-mysql-gives-general-error-1390-prepared-statement-con)
or
[codesec](http://www.codesec.net/view/194898.html) 
or [baidusearch](https://www.baidu.com/s?ie=UTF-8&wd=Prepared%20statement%20contains%20too%20many%20placeholders)

**Comment by andeya** [comment]
已修复。
https://github.com/henrylee2cn/pholcus/commit/5dab2741ecb0647529017b539dd4b1fca9e30ae0

**Pull request closed without merging**
